# Step 1: Make that table and populate it
drop table if exists pbp2014_d1;

CREATE TABLE `ncaa_baseball`.`pbp2014_d1`
(
	`unique_id` Integer primary key,
	`year_id` Integer null,
	`div_id` Integer null,
	`game_id` Integer null,
	`inning` Integer null,
	`home_bats` Integer null,
	`event_seq` Integer null,
	`road_text` Varchar(455) null,
	`road_score` Integer null,
	`home_score` Integer null,
	`home_text` Varchar(455) null,
	`bat_name` Varchar(80) null,
	`run1_name` Varchar(80) null,
	`run2_name` Varchar(80) null,
	`run3_name` Varchar(80) null,
	`sub_in` Varchar(255) null,
	`sub_pos` Integer null,
	`sub_out` Varchar(255) null,
	`base_cd_before` Integer null,
	`outs_before` Integer null,
	`event_str` Varchar(99) null,
	`balls` Integer null,
	`strikes` Integer null,
	`pitch_str` Varchar(25) null,
	`base_cd_after` Integer null,
	`outs_after` Integer null,
	`rbi` Integer null,
	`uer` Integer null,
	`tm_uer` Integer null,
	`ab_fl` Integer null,
	`pa_fl` Integer null,
	`bat_event_fl` Integer null,
	`bip_fl` Integer null,
	`event_cd` Integer null,
	`hit_cd` Integer null,
	`hit_type` Varchar(5) null,
	`hit_loc` Varchar(12) null,
	`bunt_fl` Integer null,
	`sf_fl` Integer null,
	`sh_fl` Integer null,
	`sb_fl` Integer null,
	`cs_fl` Integer null,
	`pk_fl` Integer null,
	`asst1` Integer null,
	`asst2` Integer null,
	`asst3` Integer null,
	`asst4` Integer null,
	`asst5` Integer null,
	`asst6` Integer null,
	`putout1` Integer null,
	`putout2` Integer null,
	`putout3` Integer null,
	`error1` Integer null,
	`error2` Integer null,
	`error3` Integer null,
	`err1_type` Varchar(5) null,
	`err2_type` Varchar(5) null,
	`err3_type` Varchar(5) null,
	`inn_st_fl` Integer null,
	`inn_end_fl` Integer null,
	`inn_runs_before` Integer null,
	`runs_on_play` Integer null,
	`runs_this_inn` Integer null
);

# THIS WILL OBVIOUSLY NEED TO BE CHANGED TO MATCH YOUR DIRECTORY STRUCTURE!
LOAD DATA INFILE 'C:\\Retrosheet\\ncaa\\events_2014_D1.dat' INTO TABLE pbp2014_d1 FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n' IGNORE 1 LINES;

# oooh, ahhhh
SELECT * FROM pbp2014_d1;
select * from games2014;